name: 'Terraform Validation'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TF_LOG : "debug"

jobs:
  terraform-validate:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.8.0'

    - name: Terraform Format Check
      run: |
        echo "Running terraform fmt check..."
        if ! terraform fmt -check -recursive -diff; then
          echo "::error::Terraform formatting errors found. Please run 'terraform fmt -recursive' locally to fix formatting."
          echo "Files with formatting issues are listed above with their differences."
          exit 1
        fi
