name: 'Terraform Validation'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-validate:
    name: 'Terraform Validation'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.8.0'

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Validate Terraform Modules
      run: |
        for dir in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u); do
          echo "Validating Terraform files in: $dir"
          cd $dir
          terraform init -backend=false
          terraform validate
          cd - > /dev/null
        done
